version: '2.1'
services:
  restify:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/home/node/app
    command: "npx nodemon app/main.js"
