version: '2.1'
services:
  flask:
    image: quay.io/azavea/flask:1.0-python3.6-slim
    working_dir: /usr/src
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src
    command:
      - "--workers=2"
      - "--bind=0.0.0.0:8080"
      - "--reload"
      - "--log-level=debug"
      - "--access-logfile=-"
      - "--error-logfile=-"
      - "-kgevent"
      - "main:app"
